var drawBorders = function() {
  var x = 0.5;
  var y = 32.5;

  context.strokeStyle = "#6800FF";
  context.lineWidth = 1;

  // Outer border
  context.beginPath();
  context.moveTo(x, y);
  context.quadraticCurveTo(x, y -= 8, x += 8, y);
  context.lineTo(x += 207, y);
  context.quadraticCurveTo(x += 8, y, x, y += 8);
  context.lineTo(x, y += 63);
  context.quadraticCurveTo(x, y += 8, x -= 8, y);
  context.lineTo(x -= 31, y);
  context.moveTo(--x, ++y);
  context.lineTo(x, y += 23);
  context.moveTo(++x, ++y);
  context.lineTo(x += 40, y);
  context.moveTo(x, y += 23);
  context.lineTo(x -= 40, y);
  context.moveTo(--x, ++y);
  context.lineTo(x, y += 23);
  context.moveTo(++x, ++y);
  context.lineTo(x += 31, y);
  context.quadraticCurveTo(x += 8, y, x, y += 8);
  context.lineTo(x, y += 79);
  context.quadraticCurveTo(x, y += 8, x -= 8, y);
  context.lineTo(x -= 207, y);
  context.quadraticCurveTo(x -= 8, y, x, y -= 8);
  context.lineTo(x, y -= 79);
  context.quadraticCurveTo(x, y -= 8, x += 8, y);
  context.lineTo(x += 32, y);
  context.moveTo(++x, --y);
  context.lineTo(x, y -= 23);
  context.moveTo(--x, --y);
  context.lineTo(x -= 40, y);
  context.moveTo(x, y -= 23);
  context.lineTo(x += 40, y);
  context.moveTo(++x, --y);
  context.lineTo(x, y -= 23);
  context.moveTo(--x, --y);
  context.lineTo(x -= 32, y);
  context.quadraticCurveTo(x -= 8, y, x, y -= 8);
  context.lineTo(x, y -= 63);

  // Inner border
  context.moveTo(x += 3, y);
  context.lineTo(x, y -= 3);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 100, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 28);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x += 4, y);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x, y -= 28);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 101, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 69);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 36, y);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x, y += 27);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x += 41, y);
  context.moveTo(x, y += 17);
  context.lineTo(x -= 41, y);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x, y += 27);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x += 36, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 36);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 14, y);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x, y += 4);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x += 14, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 37);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 213, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 37);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 14, y);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x, y -= 4);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x -= 14, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 36);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 37, y);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x, y -= 27);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x -= 42, y);
  context.moveTo(x, y -= 17);
  context.lineTo(x += 42, y);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x, y -= 27);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x -= 37, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 69);

  // Internal obstacles
  context.moveTo(x += 17, y += 19);
  context.lineTo(x, y -= 2);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 19, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 11);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 19, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 11);

  context.moveTo(x += 40, y += 2);
  context.lineTo(x, y -= 2);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 27, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 11);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 27, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 11);

  context.moveTo(x += 72, y += 2);
  context.lineTo(x, y -= 2);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 27, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 11);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 27, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 11);

  context.moveTo(x += 48, y += 2);
  context.lineTo(x, y -= 2);
  context.lineTo(x += 2, y -= 2);
  context.lineTo(x += 19, y);
  context.lineTo(x += 2, y += 2);
  context.lineTo(x, y += 11);
  context.lineTo(x -= 2, y += 2);
  context.lineTo(x -= 19, y);
  context.lineTo(x -= 2, y -= 2);
  context.lineTo(x, y -= 11);

  // Ghost house
  context.moveTo(x = 84.5, y = 124.5);
  context.lineTo(x += 19, y);
  context.lineTo(x, y += 3);
  context.lineTo(x -= 16, y);
  context.lineTo(x, y += 26);
  context.lineTo(x += 50, y);
  context.lineTo(x, y -= 26);
  context.lineTo(x -= 16, y);
  context.lineTo(x, y -= 3);
  context.lineTo(x += 19, y);
  context.lineTo(x, y += 32);
  context.lineTo(x -= 56, y);
  context.lineTo(x, y -= 32);

  context.stroke();
}
